BloomFilter:BloomFilter.cpp BloomFilter.h Hash.h Hash.cpp main.cpp
	g++ BloomFilter.cpp Hash.cpp main.cpp -o BloomFilter
run:BloomFilter emaillist.dat checklist.dat
	./BloomFilter emaillist.dat checklist.dat resultlist.dat
